c-blake/cligen

- cligen.nim
- cligen/argcvt.nim
* fixes issue mentioned in this comment: https://github.com/c-blake/cligen/issues/54#issuecomment-443390541
```
the default value formatting for seq params is not good:
* newlines are not escaped, unlike for non-seq string params (see D20181130T172327)
* @[""] prints as nothing_at_all (for DPSV, )
* @[] prints as EMPTY (for DPSV, EMPTY, which is not super consistent)
* it's ambiguous, eg when delimiter = " " (a space), default value for @["", ""] is indistinguishable from default value for @[""] (admittedly, this is rare scenario but still)
```
nim c -r -d:case11 $vitanim_D/testcases/tests/t0000.nim -h
```
Usage:
main [required&optional-params]
Options(opt-arg sep :|=|spc):
-h, --help                                 print this help
--help-syntax                              print …
```
> unambiguous default value printing

- cligen/argcvt.nim
- cligen/textUt.nim
- test/EchoResult.nim
- test/HashSets.nim
- test/ResultInt.nim
cligen fails on 0.19.6
```
~/.nimble/pkgs/cligen-0.9.26/cligen/textUt.nim(7, 13) Error: cannot open file: std/wordwrap
```
> Fix detection of stable

- cligen/sysUt.nim
See https://github.com/nim-lang/Nim/pull/12321 and https://github.com/nim-lang/Nim/issues/12187
> Prepare for csize to be changed to uint

- cligen.nim
Signed-off-by: David Krause <david@code0.xyz>
i am by far an macro expert and this maybe has side effects that i'm unaware of.
But it seems to work.
```nim
import cligen
const help = """
help
====
my 
help
"""
proc foo() = discard
dispatch(foo, doc = help)
```
> allow const variables to be used as doc; fixes #110

- cligen/clCfgInit.nim
- cligen/clCfgToml.nim
To enable reading from a TOML config file, the user needs to:
1. Install the parsetoml package using `nimble install parsetoml`
2. Compile the project using cligen with `-d:clCfgToml`
Default location for the TOML config file: ${XDG_CONFIG_HOME}/cligen/config.toml
> Allow parsing cligen config from a TOML file

- cligen/macUt.nim
Upcoming changes to Nim compiler will make proc params symbols instead of idents. Package tests showed cligen changes are required.
https://github.com/nim-lang/Nim/pull/15252
https://github.com/nim-lang/Nim/pull/15332
> Support proc params as sym

- .github/workflows/gh-pages.yml
- .github/workflows/test.yml
- test.sh
- test/ref
- Version up 'setup-nim-action'
- Skip test on 'macOS' VM because devel-compiler doesn't exist
- Remove compiler-message from 'test/ref'
- Change test script
The current test script writes '--help' message and compiler message to 'test/out'.
It is difficult to ignore with 'grep'.
So I split 'compile' phase and 'run' command phase.
> fix test script #165

- cligen/textUt.nim
also strip osc codes. required for https://github.com/c-blake/lc/pull/2
now the name of the procedure doesn't reflect its behavior exactly. should i rename?
> Strip OSC codes

- cligen.nim
/cc @c-blake 
that was the only package that broke in https://github.com/nim-lang/Nim/pull/17807; the code here is forward and backward compatible wrt https://github.com/nim-lang/Nim/pull/17807, and is regardless of https://github.com/nim-lang/Nim/pull/17807 an improvement as it avoids a call to `compiles()` which causes extra compilation for the underlying expression
the `p()` in `compiles(type(p()))` seems suspicious given that `p` is apparently called also via `p(hlp, usage=use, prefix=pfx, skipHelp=skipHlp, noHdr=noUHdr)`, but that's a pre-existing issue unrelated to this PR
> unblock nim https://github.com/nim-lang/Nim/pull/17807 typeof(voidExpr)

- cligen.nim
The docs still had the superseded "SUPPRESS" value for `hTabSuppress`.
Also expanded wording a bit.
> Update default `hTabSuppress` value in docs

- README.md
- cligen.nim
Expands on using `help` and `short` macro parameters.
Updates the help suppression string in Readme.
Closes #194
> Readme and documentation fixes.

- cligen/mslice.nim
- cligen/osUt.nim
This adds two helpers to more easily use `seq[T]` types together with `procpool`.
1. `wrLenSeq` similar to `wrLenBuf`. Writes the `seq[T]` (as long as `T` is flat, use at your own risk) with an integer length prefix using `writev` to a given file descriptor.
2. `toSeq` for `MSlice`. Copies over the data in the given slice to a sequence of `seq[T]` (again, flat `T`). 
Combined they can be used to easily write data from a kid worker back to the parent and fill a resulting sequence.
Until we have an example using this in the repository, here's a snippet of the main parts of my own code for which I just wrote this (it's a MC code where I parallelize over multiple processes to draw more toys).
```nim
type
ProcData = object
id: int
nmc: int
proc computeParallelLimits(ctx: Context, limitKind: …
```
> `procpool` helpers for flat `seq[T]` types

- cligen/mslice.nim
This is similar to the `readLine` procedure for the `Stream` type in
the stdlib, except working on slices.
The implementation is obviously directly based on the `mSlices` iterator. Initially I wanted to base one on the other, but I decided against it for now. This way I can add a `nil` check in `nextSlice` and don't need to shadow the input `mslc` argument in `mSlices` to have a slice that we advance for each yielded slice.
> add `nextSlice` helper to advance slice to sep and store in a given mutable slice

- cligen/sysUt.nim
ref https://github.com/nim-lang/Nim/pull/20070
Imo, `shallowCopy` only works for string/seq and is about to be removed for ARC/ORC. Inn this case, `move` is better.
> replace shallowCopy with move

- cligen/unixUt.nim
Return type of  `getxattr` and `extattr_get_file` is `ssize_t` which is (long) int.
> Fix csize definition

- GNUmakefile
`--warning[all]:off` has been added in one of later versions; should use `--warnings:off` instead for compatibility (and it’s shorter, by the way).
By default, Nim compiles generated C code in multiple processes. Since we’d like to give the user invoking our Makefile control over how much concurrency they want (`-j`), we pass `--parallelBuild:1` (i.e., one-threaded) to Nim.
> Respect `-j` in the Makefile

- GNUmakefile
- test.sh
- test/FancyRepeats.nim
- test/FancyRepeats2.nim
- test/ListDecl.nim
- test/nim.cfg
So I did what we discussed in #225. I put `GcUnsafe` and `GlobalVar` in `nim.cfg` since cligen uses global variables; there’s nothing a person who wishes to run tests can do with it. `Deprecated` remained in `GNUMakefile`/`test.sh` so you can easily run without it via `w= ./test.sh`; and so did `ProveField` (arguable; might be better to move it to `nim.cfg` too).
As to a strange cat in the pipeline, I suspect you tried `2>&1 >$o`, and it didn’t work because the order of redirections is important. They are processed from left to right: first, stderr is sent to where stdout is _currently_ connected to; then, stdout is redirected to a file. And we want this to happen vice versa. (I ran `test.sh` without final `&`, and the tests passed.)
`hint[Performance]` is indeed issued at a later stage …
> Enable most warnings for tests

- cligen/strUt.nim
- examples/tmpl.nim
- util/complgen.nim
`tmplParse` is a brilliant: its syntax is so flexible yet can be parsed with a few `memchr` calls and an ident-skipping loop. Unfortunately, current implementation is suboptimal and even buggy. I tried to fix/improve it:
1. `${(id)arg}` syntax did not work _at all_ because `a1` was never assigned in the corresponding branch. If you tried to access `fmt[arg]`, you got a `Defect`. Fixed.
2. `${(}a)b}` was parsed as a call with _id=_`}a`, _arg=garbage_, _call=_`${(}`, followed by text `a)b}`. That behaviour feels weird to me. I think these three options are more sensible:
1. _id=_`}a`, _arg=_`b`, _call=_`${(}a)b}`. I.e., the first `}` is not treated as a closer for the whole call.
2. _id=_`(`, _arg=empty_, _call=_`${(}`; followed by text `a)b}`. I.e., the first `}` does close the call, and …
> Improvements to `strUt.tmplParse`

- cligen/macUt.nim
Hi, thanks for the awesome library!
In order to use [release-please](https://github.com/google-github-actions/release-please-action), I need to add a comment on the `version = ` line in `xxx.nimble`.
Example: https://github.com/pysan3/minorg/blob/main/minorg.nimble
Currently, the `fromNimble` function does not take that into account, and the function returns what is not intended. i.e. `file.fromNimble("version")` -> `2.0.1" # {x-release-please-version`
This PR fixes the problem by cutting the comment before returning, as well as some minor fixes to the function.
Hope this helps ;)
> fix(macUt): ignore comments in nimble file

- cligen/argcvt.nim
`doArgParse` takes 2 generic parameters, but in `argParse` for each number type, only 1 is given, which compiles due to bugs in Nim. To safeguard against the Nim compiler, the missing generic parameter is now provided.
> fix generic instantiations of `doArgParse`

- cligen.nim
- cligen/argcvt.nim
- cligen/clCfgInit.nim
- cligen/clCfgToml.nim
When this option is enabled, string defaults will not be quoted if they are non empty and do not contain any characters that would require quoting them when using the command line (e.g. when they do not contain spaces, new lines, globs, etc.)
> Introduce "minStrQuoting" option to only quote string defaults when necessary

- .gitignore
That folder is created by JetBrains' editors and should not be included in the repository.
> Add the .idea folder to gitignore

- RELEASE-NOTES.md
- cligen.nim
- cligen/clCfgInit.nim
- cligen/clCfgToml.nim
- cligen/textUt.nim
- test/PassValuesMulti.nim
- test/ref
Replace `textUt.ttyWidth = width` with a more fine-grained control mechanism of `wrapDoc`, `wrapTable`.  Special values of `0` mean the old auto-terminal-width wrapping, `-1` means never wrap at all, and other values mean to wrap at that column (including indent). Update both config file parsers to allow CLusers to tweak settings.
Update `test/PassValuesMulti.nim` with some example code showing 4 different wrap columns in play.  Update reference output in light of both `cligen.nim` edits and new `PassValuesMulti` help output.  Also update RELEASE_NOTES.md with details for CLauthors and revert the description (& implementation) of `var ttyWidth` in `textUt.nim` since it is less general.
> Replace `textUt.ttyWidth = width` with a more fine-grained control

- cligen.nim
- test/PassValues.nim
Also avoid adding the usage header at the top of the help message when the usage template string is customized and the $usehdr template variable (or the _default_ "Usage:\n" header) is used in it.
Note that this does not change the default behavior in any way. It only makes it easier to completely customize the help message by simply changing the usage template string without having to also set the `noHdr` flag.
> Add $usehdr template variable
